version: "3.8"
services:
  alpine1:
    image: alpine:latest
    container_name: alpine1
    networks:
      - boutique
    entrypoint: /bin/sh
    command: -c "sleep 1000"
    tty: true

  alpine2:
    image: alpine:latest
    container_name: alpine2
    networks:
      - boutique
    entrypoint: /bin/sh
    command: -c "sleep 1000"
    tty: true

networks:
  boutique:
    name: boutique